## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - nightly
notifications:
  email: false
git:
  depth: 99999999
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("Capstan")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
